- name: Update cache
  when: install_dependencies_update_cache
  block:
    - name: Update apt
      when: ansible_os_family == 'Debian'
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
    - name: Panic
      when: ansible_os_family != 'Debian'
      ansible.builtin.fail:
        msg: "Unsupported OS family: {{ ansible_os_family }}"

- name: Install dependencies
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ dependencies }}"
