- name: Generate SSH keys
  block:
    - name: Generate RSA key for {{ item.alias }}
      community.crypto.openssh_keypair:
        path: "{{ home }}/.ssh/{{ item.alias }}_id_rsa"

    - name: Print public key
      block:
        - name: Read remote file content
          ansible.builtin.slurp:
            src: "{{ home }}/.ssh/{{ item.alias }}_id_rsa.pub"
          register: file_content

        - name: This one for GHE
          ansible.builtin.debug:
            msg: "{{ file_content.content | b64decode }}"

    - name: Add github.tmc-stargate.com in the configuration
      community.general.ssh_config:
        user: "{{ primary_user }}"
        host: "{{ item.host }}"
        hostname: "{{ item.hostname | default(item.host) }}"
        identity_file: "{{ home }}/.ssh/{{ item.alias }}_id_rsa"
        state: present
