- name: Onboard DevPCs
  vars:
    environment: production
  hosts: devpcs
  roles:
    - role: install_dependencies
      become: true
      vars:
        install_dependencies_update_cache: true
    - create_directories
    - nvim
    - role: configure_nvim
      vars:
        configure_nvim_force_pull: true
    - fzf
    - eza
    - oh_my_posh
    - configure_oh_my_posh
    - lazygit
    - configure_lazygit
    - configure_git
    - configure_tmux
    - configure_zsh
