- name: Onboard DevPCs
  hosts: devpcs
  roles:
    - role: install_dependencies
      become: true
      vars:
        install_dependencies_update_cache: true
    - create_directories
    - fzf
    - eza
    - oh_my_posh
    - lazygit
