- name: Upload zsh config
  ansible.builtin.copy:
    src: "{{ inventory_dir }}/dotfiles/dotfiles/.zshrc"
    dest: "{{ configure_zsh_config }}"
    owner: "{{ primary_user }}"
    group: "{{ primary_user }}"
    mode: "0644"
